---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - limitranges
  - resourcequotas
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ksquad.io
  resources:
  - agentruntimes
  - agents
  - egresspolicies
  - mcpservers
  - roles
  - skills
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ksquad.io
  resources:
  - mcpservers/status
  - projects/status
  - teams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ksquad.io
  resources:
  - projects
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ksquad.io
  resources:
  - teams
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ksquad.io
  resources:
  - teams/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
