/*
Copyright 2026 The K8squad Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// Common reference types shared by the squad-composition CRDs (story 1.2,
// arch §5.1). Refs are deliberately light: a name plus an optional namespace,
// never Kubernetes OwnerReferences — ownership/GC semantics are a reconciler
// concern (story 1.3) — and never pointers into the coordination Postgres,
// whose only CRD bridge is Run.spec.workItemRef / Run.status.artifactRefs
// as opaque references (ADR-001/ADR-002).

// ObjectRef is a light cross-CRD reference to another ksquad.io object.
type ObjectRef struct {
	// Name of the referenced object.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace of the referenced object. Empty means the referring object's
	// own namespace.
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

// SecretRef references a Kubernetes Secret by name plus an optional key inside
// it. All credentials ride the per-user BYO-Secret discipline (arch §11).
type SecretRef struct {
	// Name of the referenced Secret.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Key inside the Secret; empty means the consumer-defined default key.
	// +optional
	Key string `json:"key,omitempty"`
}

// ContextBudget is a per-tier token allocation for the §8.5 context envelope.
// The Context Assembler resolves Project default → Agent override → Run
// dynamic trim, clamped by the resolved model contextWindow (§10.1); a budget
// above the model window is a fail-closed validation error enforced by the
// reconciler (story 1.3). Pointer fields mean "inherit from the next level up
// in the resolution order" when unset.
//
// Admission-level sanity (story 1.3): a tier set to a negative allocation is
// rejected fail-closed via CEL.
// +kubebuilder:validation:XValidation:message="context budget tiers must be >= 0 when set; remove or raise the negative tier",rule="(!has(self.workItem) || self.workItem >= 0) && (!has(self.projectDocs) || self.projectDocs >= 0) && (!has(self.memoryRecall) || self.memoryRecall >= 0) && (!has(self.artifacts) || self.artifacts >= 0)"
type ContextBudget struct {
	// WorkItem tier allocation. Must-include content (work item + acceptance
	// criteria + goals) is never truncated (§8.5).
	// +optional
	WorkItem *int64 `json:"workItem,omitempty"`

	// ProjectDocs tier allocation (architecture docs, conventions).
	// +optional
	ProjectDocs *int64 `json:"projectDocs,omitempty"`

	// MemoryRecall tier allocation (scoped §7 semantic recall, untrusted
	// provenance tier).
	// +optional
	MemoryRecall *int64 `json:"memoryRecall,omitempty"`

	// Artifacts tier allocation (build outputs, PR refs from the §5.4 mirror).
	// +optional
	Artifacts *int64 `json:"artifacts,omitempty"`
}

// CapabilityOverrides adjust the capabilities advertised on the generated
// Agent Card (arch §10.1) relative to what the resolved AgentRuntime
// advertises (docker / github / packageInstall / byoModelEndpoint /
// interactive-prompt / ...). The card is generated by the Agent reconciler
// (story 1.3); these overrides are the declarative input.
type CapabilityOverrides struct {
	// Allow turns capabilities on in addition to the resolved runtime's
	// advertised set.
	// +optional
	Allow []string `json:"allow,omitempty"`

	// Deny turns capabilities off; Deny wins over Allow (enforced by the
	// Agent reconciler, story 1.3).
	// +optional
	Deny []string `json:"deny,omitempty"`
}

// FallbackModel names a secondary model the shim switches to mid-Run on a
// rate_limited signal (arch §8 tier-1 recovery, §10.3, ADR-030/ADR-031).
// Absent a fallback, recovery falls to the scheduled-timer pause (§8).
type FallbackModel struct {
	// Model is the secondary model name.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Model string `json:"model"`

	// ModelEndpointRef optionally gives the fallback its own BYO endpoint
	// Secret (§10.3). Unset means the fallback resolves against the Agent's
	// own endpoint.
	// +optional
	ModelEndpointRef *SecretRef `json:"modelEndpointRef,omitempty"`
}
